domains:
  localhost:
    rclone:
      remote: test
      flags: []

  shuto.test:
    rclone:
      remote: webdav
      flags:
        - --webdav-url=${RCLONE_CONFIG_SERVER_URL}
        - --webdav-vendor=${RCLONE_CONFIG_SERVER_VENDOR}
        - --webdav-user=${RCLONE_CONFIG_SERVER_USER}
        - --webdav-pass=${RCLONE_CONFIG_SERVER_PASS}
    security:
      mode: hmac_timebound
      secrets:
        - key_id: "v1"
          secret: "${HMAC_SECRET_KEY}"
      validity_window: 300 # 5 minutes
      api_keys:
        - key: "${SHUTO_TEST_API_KEY_1}"
          description: "Shuto Test API Key 1"
        - key: "${SHUTO_TEST_API_KEY_2}"
          description: "Shuto Test API Key 2"
